theme: jekyll-theme-cayman
title: Revisiting The Spectral & Timing Properties of NGC 4151
description: Analysis details for the paper (https://arxiv.org/abs/1908.09862) published in the Astrophysical Journal, including data description and codes.
