theme: jekyll-theme-cayman
title: Revisiting The Spectral & Timing Properties of NGC 4151
description: Analysis detailes for the paper published in the Astrophysical Journal, including data description and codes.
